import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('fa')];
  static const delegate = _AppStringsDelegate();

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings)!;

  String text(String key) =>
      (_values[locale.languageCode] ?? _values['en']!)[key] ??
      _values['en']![key] ??
      key;

  static const _values = <String, Map<String, String>>{
    'en': {
      'home': 'Home',
      'servers': 'Servers',
      'settings': 'Settings',
      'logs': 'Logs',
      'selectedServer': 'Selected server',
      'noServer': 'No server available',
      'status': 'Connection status',
      'disconnected': 'Disconnected',
      'preparing': 'Preparing',
      'connecting': 'Connecting',
      'connected': 'Connected',
      'switching': 'Switching…',
      'restarting': 'Restarting…',
      'reconnecting': 'Reconnecting',
      'stopping': 'Stopping',
      'error': 'Error',
      'publicIp': 'Public IP',
      'checking': 'Checking…',
      'unknown': 'Unknown',
      'subscription': 'Subscription',
      'used': 'Used',
      'remaining': 'Remaining',
      'unlimited': 'Unlimited',
      'expired': 'Expired',
      'expires': 'Expires',
      'connect': 'Connect',
      'disconnect': 'Disconnect',
      'restartService': 'Restart Service',
      'retryCore': 'Retry Core',
      'ping': 'Ping',
      'subscriptionUsage': 'Subscription usage',
      'refresh': 'Update now',
      'updateSubscription': 'Update Subscription',
      'notConfigured': 'Subscription endpoint is not configured.',
      'configureHint':
          'Set NIRANG_SUBSCRIPTION_URL in android/gradle.properties or the build environment.',
      'testAll': 'Test all',
      'cancel': 'Cancel',
      'testLatency': 'Test latency',
      'tcpPing': 'TCP Ping',
      'select': 'Select',
      'selected': 'Selected',
      'basicInfo': 'Basic information',
      'serverInformation': 'Server information',
      'serverActions': 'Server actions',
      'timeout': 'Timeout',
      'failed': 'Failed',
      'testing': 'Testing…',
      'neverTested': 'Not tested',
      'idle': 'Not tested',
      'success': 'Available',
      'protocol': 'Protocol',
      'transport': 'Transport',
      'routing': 'Routing',
      'dns': 'DNS',
      'name': 'Name',
      'security': 'Security',
      'country': 'Country',
      'port': 'Port',
      'generalInformation': 'General information',
      'protectedCredentials': 'Protected credentials',
      'credentialsProtected':
          'Sensitive values are intentionally masked and cannot be copied or changed.',
      'password': 'Password',
      'realityPublicKey': 'Reality public key',
      'shortId': 'Short ID',
      'delete': 'Delete',
      'deleteServer': 'Delete server?',
      'deleteServerBody':
          'This server will be hidden locally until the next successful subscription update.',
      'restoreDeletedServers': 'Restore deleted servers',
      'noDeletedServers': 'No locally deleted servers',
      'deletedServersCount': 'locally deleted server(s)',
      'serversRestored': 'Deleted servers restored',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'performanceMode': 'Performance Mode',
      'performanceModeSummary':
          'Reduce blur and heavy visual effects while keeping lightweight animations.',
      'language': 'Language',
      'english': 'English',
      'persian': 'فارسی',
      'global': 'Global proxy',
      'globalRoutingHint':
          'Send all non-DNS traffic through the selected proxy.',
      'bypassIran': 'Bypass Iran',
      'bypassIranHint':
          'Send .ir domains, Iran IP ranges, LAN and local destinations directly.',
      'custom': 'Custom routing',
      'customRuleHint': 'Listed domains and IP ranges connect directly.',
      'direct': 'Direct',
      'customDomains': 'Direct domains',
      'customIps': 'Direct IP / CIDR rules',
      'ruleHint': 'Comma or line separated rules',
      'save': 'Save',
      'apply': 'Apply',
      'requiredValue': 'A value is required.',
      'invalidDns': 'Enter a valid IP address or DNS hostname.',
      'invalidHttps': 'Enter a valid HTTPS URL.',
      'invalidRules': 'The rule text is invalid or too large.',
      'invalidPort': 'Enter distinct ports from 1024 to 65535.',
      'localPortConflict': 'Local proxy port is already in use',
      'localPortConflictSummary':
          'v2rayN or another proxy client may be using the niraN SOCKS/HTTP ports. Close it, retry, or choose different ports.',
      'changePorts': 'Change Ports',
      'retry': 'Retry',
      'invalidVpnAddress': 'Enter a private IPv4 interface address with CIDR.',
      'vpnSettings': 'VPN settings',
      'systemProxySettings': 'Windows System Proxy',
      'windowsSystemProxy': 'HTTP proxy on 127.0.0.1:10809',
      'systemProxyMode': 'System Proxy',
      'tunMode': 'TUN Mode',
      'setSystemProxy': 'Set System Proxy',
      'setSystemProxySummary':
          'Point Windows System Proxy to the running niraN HTTP proxy.',
      'tunIndependentSummary':
          'Enable Windows TUN independently from the System Proxy setting.',
      'clearSystemProxy': 'Clear System Proxy',
      'clearSystemProxySummary':
          'Disable a stuck Windows proxy and clear niraN recovery data.',
      'systemProxyEnabledToast': 'System Proxy enabled',
      'systemProxyClearedToast': 'System Proxy cleared',
      'showRecentLogsOnHome': 'Show recent logs on Home',
      'showRecentLogsOnHomeSummary':
          'Show a compact live view of the latest sanitized Core events.',
      'startWithWindows': 'Start niraN with Windows',
      'startWithWindowsSummary':
          'Launch this portable copy automatically when you sign in.',
      'recentLogs': 'Recent logs',
      'connectionMode': 'Connection mode',
      'vpn': 'VPN mode',
      'proxy': 'Proxy mode',
      'enableLocalDns': 'Enable local DNS',
      'enableLocalDnsSummary': 'Route DNS traffic through the Xray DNS module.',
      'enableFakeDns': 'Enable FakeDNS',
      'enableFakeDnsSummary': 'Use synthetic DNS results with Xray sniffing.',
      'vpnDns': 'VPN DNS',
      'vpnInterfaceAddress': 'VPN interface address',
      'vpnInterfaceIpv6Address': 'VPN IPv6 interface address',
      'invalidVpnIpv6Address':
          'Enter a valid IPv6 interface address with CIDR.',
      'localSocksPort': 'Local SOCKS port',
      'localHttpPort': 'Local HTTP port',
      'realPingConcurrency': 'Concurrent real-delay tests',
      'realDelayUrl': 'Real-delay test URL',
      'realDelayTimeout': 'Real-delay timeout',
      'delayTest': 'Delay test',
      'localProxy': 'Local proxy',
      'tunSettings': 'TUN settings',
      'invalidUrl': 'Enter a valid HTTP or HTTPS URL.',
      'coreSettings': 'Core settings',
      'advancedSettings': 'Advanced settings',
      'enableIpv6': 'Enable IPv6',
      'enableIpv6Summary':
          'Allow Xray to resolve and connect to IPv6 destinations.',
      'preferIpv6': 'Prefer IPv6',
      'preferIpv6Summary':
          'Prefer IPv6 when resolving the proxy server address.',
      'vpnMtu': 'VPN MTU',
      'vpnMtuSummary': 'Valid range: 1280–9000',
      'enableSniffing': 'Enable sniffing',
      'sniffingSummary':
          'Detect destination domains from HTTP, TLS and QUIC traffic.',
      'enableRouteOnly': 'Enable routeOnly',
      'routeOnlySummary':
          'Use sniffed domains for local routing without replacing the target address.',
      'blockQuic': 'Block QUIC (UDP/443)',
      'blockQuicSummary':
          'Optional compatibility fallback. Disabled by default.',
      'mux': 'Mux',
      'muxSummary':
          'Multiplex compatible VLESS/VMess connections. Disabled by default.',
      'muxConcurrency': 'Mux concurrency',
      'remoteDns': 'Remote DNS',
      'directDns': 'Direct DNS',
      'directDnsSummary': 'Use a dedicated resolver for direct destinations.',
      'directDnsAddress': 'Direct DNS address',
      'dnsQueryStrategy': 'DNS query strategy',
      'dnsQueryStrategySummary': 'Address families returned by Xray DNS.',
      'dnsParallelQuery': 'Parallel DNS query',
      'dnsParallelQuerySummary': 'Query eligible resolvers concurrently.',
      'dnsServeStale': 'Serve stale DNS',
      'dnsServeStaleSummary':
          'Use an expired cached answer while it refreshes.',
      'directTargetStrategy': 'Direct target resolution',
      'proxyTargetStrategy': 'Proxy target resolution',
      'proxyDialStrategy': 'Proxy dial resolution',
      'happyEyeballs': 'Happy Eyeballs',
      'happyEyeballsSummary': 'Race IPv4 and IPv6 proxy addresses over TCP.',
      'resetSettings': 'Reset settings',
      'resetSettingsBody': 'Restore all niraN settings to their defaults?',
      'settingsReset': 'Settings were reset.',
      'domainStrategy': 'Domain strategy',
      'subscriptionUpdate': 'Subscription updates',
      'autoUpdate': 'Auto update',
      'updateInterval': 'Update interval',
      'lastUpdated': 'Last updated',
      'updates': 'Updates',
      'currentVersion': 'Current version',
      'checkForUpdates': 'Check for updates',
      'newVersionAvailable': 'New version available',
      'viewRelease': 'View release',
      'upToDate': "You're up to date.",
      'updateCheckFailed':
          'Could not reach GitHub. Check your connection and try again.',
      'updateDownload': 'Update download',
      'downloading': 'Downloading',
      'paused': 'Paused',
      'cancelled': 'Cancelled',
      'verifying': 'Verifying',
      'downloaded': 'Downloaded',
      'readyToUpdate': 'Ready to update',
      'closingApp': 'Closing app',
      'extracting': 'Extracting',
      'replacingFiles': 'Replacing files',
      'renamingFolder': 'Renaming folder',
      'restartingApp': 'Restarting',
      'updateFailed': 'Update failed',
      'completed': 'Completed',
      'cancelDownload': 'Cancel download',
      'resumeDownload': 'Resume download',
      'installUpdate': 'Install update',
      'openDownloadFolder': 'Open download folder',
      'performanceModeDialogBody':
          'If your device is older or the interface feels slow, Performance Mode can reduce visual effects and animations to improve responsiveness and battery usage.',
      'enable': 'Enable',
      'keepFullEffects': 'Keep full effects',
      'hours6': '6 hours',
      'hours12': '12 hours',
      'hours24': '24 hours',
      'never': 'Never',
      'telegram': 'Telegram channel',
      'telegramSubtitle': 'Updates, outages and server news',
      'joinTelegramTitle': 'Stay informed',
      'joinTelegramBody':
          'Join our Telegram channel to receive updates, outages and server news.',
      'joinTelegram': 'Join Telegram',
      'later': 'Later',
      'dontShowAgain': "Don't show again",
      'about': 'About',
      'coreVersion': 'Xray core',
      'packageName': 'Package ID',
      'noLogs': 'No logs yet',
      'clear': 'Clear',
      'clearLogs': 'Clear logs?',
      'clearLogsBody': 'This removes locally stored, redacted app events.',
      'operationFailed': 'Operation failed',
      'administratorRequiredTitle': 'Administrator permission required',
      'administratorRequiredMessage':
          'TUN mode requires administrator permission. Please close niraN and run it again using "Run as administrator".',
      'subscriptionUsageUnknown': 'Usage information unavailable',
      'serverCount': 'server(s)',
      'ipProvider': 'Current connection info test URL',
      'applyNextConnection': 'Changes apply on the next connection.',
      'copy': 'Copy',
      'logCopied': 'Log copied',
      'enableUdp': 'Enable UDP',
      'enableUdpSummary': 'Accept UDP traffic through the local SOCKS proxy.',
      'allowLanConnections': 'Allow connections from LAN',
      'allowLanConnectionsSummary':
          'Expose local proxy ports to the selected local interface.',
      'localListenAddress': 'Local listen address',
      'xrayLogLevel': 'Xray log level',
      'sniffingType': 'Sniffing protocols',
      'enableFragment': 'TLS ClientHello fragmentation',
      'fragmentSummary':
          'Route the upstream Xray connection through a Freedom fragment outbound.',
      'fragmentParameters': 'Fragment parameters',
      'fragmentPackets': 'Packets',
      'fragmentLength': 'Length range',
      'fragmentInterval': 'Interval range',
      'fragmentMaxSplit': 'Maximum split count',
      'defaultFingerprint': 'Default TLS fingerprint',
      'defaultUserAgent': 'Default WebSocket User-Agent',
      'domesticDns': 'Domestic DNS',
      'notSet': 'Not set',
      'invalidValue': 'Invalid value',
      'profileTlsSettings': 'Profile TLS/CDN settings',
      'fingerprint': 'Fingerprint',
      'cipherSuites': 'Cipher suites',
      'cipherSuitesHint': 'Colon-separated Xray TLS cipher suite names',
      'finalMaskHint': 'Raw Xray FinalMask JSON object',
      'invalidJson': 'Invalid JSON',
      'finalMaskObjectError': 'FinalMask must be a JSON object.',
      'allowInsecureUnsupported':
          'This link requests allowInsecure. Xray 26.7.28 no longer supports it; certificate verification remains enabled.',
      'copyShareLink': 'Copy share link',
      'shareLinkCopied': 'Share link copied',
      'emptyServers':
          'No supported VLESS, VMess or Trojan servers were loaded.',
    },
    'fa': {
      'home': 'خانه',
      'servers': 'سرورها',
      'settings': 'تنظیمات',
      'logs': 'گزارش‌ها',
      'selectedServer': 'سرور انتخاب‌شده',
      'noServer': 'سروری موجود نیست',
      'status': 'وضعیت اتصال',
      'disconnected': 'قطع',
      'preparing': 'در حال آماده‌سازی',
      'connecting': 'در حال اتصال',
      'connected': 'متصل',
      'switching': 'در حال تعویض سرور…',
      'restarting': 'در حال راه‌اندازی مجدد…',
      'reconnecting': 'اتصال مجدد',
      'stopping': 'در حال توقف',
      'error': 'خطا',
      'publicIp': 'آی‌پی عمومی',
      'checking': 'در حال بررسی…',
      'unknown': 'نامشخص',
      'subscription': 'اشتراک',
      'used': 'مصرف‌شده',
      'remaining': 'باقی‌مانده',
      'unlimited': 'نامحدود',
      'expired': 'منقضی‌شده',
      'expires': 'انقضا',
      'connect': 'اتصال',
      'disconnect': 'قطع اتصال',
      'restartService': 'راه‌اندازی مجدد سرویس',
      'retryCore': 'تلاش دوباره Core',
      'ping': 'پینگ',
      'subscriptionUsage': 'مصرف اشتراک',
      'refresh': 'به‌روزرسانی اکنون',
      'updateSubscription': 'به‌روزرسانی اشتراک',
      'notConfigured': 'آدرس داخلی اشتراک تنظیم نشده است.',
      'configureHint':
          'NIRANG_SUBSCRIPTION_URL را در android/gradle.properties یا محیط Build تنظیم کنید.',
      'testAll': 'تست همه',
      'cancel': 'لغو',
      'testLatency': 'تست تأخیر',
      'tcpPing': 'پینگ TCP',
      'select': 'انتخاب',
      'selected': 'انتخاب‌شده',
      'basicInfo': 'اطلاعات پایه',
      'serverInformation': 'اطلاعات سرور',
      'serverActions': 'عملیات سرور',
      'timeout': 'پایان زمان',
      'failed': 'ناموفق',
      'testing': 'در حال تست…',
      'neverTested': 'تست نشده',
      'idle': 'تست نشده',
      'success': 'در دسترس',
      'protocol': 'پروتکل',
      'transport': 'انتقال',
      'routing': 'مسیریابی',
      'dns': 'DNS',
      'name': 'نام',
      'security': 'امنیت',
      'country': 'کشور',
      'port': 'پورت',
      'generalInformation': 'اطلاعات عمومی',
      'protectedCredentials': 'اطلاعات ورود محافظت‌شده',
      'credentialsProtected':
          'مقادیر حساس عمداً پوشانده شده‌اند و قابل کپی یا تغییر نیستند.',
      'password': 'رمز عبور',
      'realityPublicKey': 'کلید عمومی Reality',
      'shortId': 'شناسه کوتاه',
      'delete': 'حذف',
      'deleteServer': 'سرور حذف شود؟',
      'deleteServerBody':
          'این سرور تا به‌روزرسانی موفق بعدی اشتراک، به‌صورت محلی پنهان می‌شود.',
      'restoreDeletedServers': 'بازیابی سرورهای حذف‌شده',
      'noDeletedServers': 'سرور حذف‌شده‌ای وجود ندارد',
      'deletedServersCount': 'سرور حذف‌شده محلی',
      'serversRestored': 'سرورهای حذف‌شده بازیابی شدند',
      'appearance': 'ظاهر',
      'theme': 'پوسته',
      'system': 'سیستم',
      'light': 'روشن',
      'dark': 'تیره',
      'performanceMode': 'حالت عملکرد',
      'performanceModeSummary':
          'کاهش محوشدگی و جلوه‌های سنگین با حفظ حرکت‌های سبک و روان.',
      'language': 'زبان',
      'english': 'English',
      'persian': 'فارسی',
      'global': 'پروکسی سراسری',
      'globalRoutingHint':
          'تمام ترافیک به‌جز DNS از پروکسی انتخاب‌شده عبور می‌کند.',
      'bypassIran': 'عبور مستقیم ایران',
      'bypassIranHint':
          'دامنه‌های ir، محدوده‌های IP ایران، شبکه محلی و مقصدهای محلی مستقیم متصل می‌شوند.',
      'custom': 'مسیریابی سفارشی',
      'customRuleHint': 'دامنه‌ها و محدوده‌های IP ثبت‌شده مستقیم متصل می‌شوند.',
      'direct': 'مستقیم',
      'customDomains': 'دامنه‌های مستقیم',
      'customIps': 'قواعد IP / CIDR مستقیم',
      'ruleHint': 'قواعد را با ویرگول یا خط جدید جدا کنید',
      'save': 'ذخیره',
      'apply': 'اعمال',
      'requiredValue': 'وارد کردن مقدار الزامی است.',
      'invalidDns': 'یک IP یا نام میزبان DNS معتبر وارد کنید.',
      'invalidHttps': 'یک آدرس HTTPS معتبر وارد کنید.',
      'invalidRules': 'متن قواعد نامعتبر یا بیش از حد بزرگ است.',
      'invalidPort': 'دو پورت متفاوت بین ۱۰۲۴ تا ۶۵۵۳۵ وارد کنید.',
      'localPortConflict': 'پورت پروکسی محلی در حال استفاده است',
      'localPortConflictSummary':
          'احتمالاً v2rayN یا یک کلاینت پروکسی دیگر از پورت‌های SOCKS/HTTP استفاده می‌کند. آن را ببندید، دوباره تلاش کنید یا پورت‌ها را تغییر دهید.',
      'changePorts': 'تغییر پورت‌ها',
      'retry': 'تلاش دوباره',
      'invalidVpnAddress': 'یک آدرس خصوصی IPv4 همراه CIDR وارد کنید.',
      'vpnSettings': 'تنظیمات VPN',
      'systemProxySettings': 'پروکسی سیستم Windows',
      'windowsSystemProxy': 'پروکسی HTTP روی 127.0.0.1:10809',
      'systemProxyMode': 'پروکسی سیستم',
      'tunMode': 'حالت TUN',
      'setSystemProxy': 'تنظیم پروکسی سیستم',
      'setSystemProxySummary':
          'اتصال پروکسی سیستم Windows به HTTP Proxy درحال اجرای niraN.',
      'tunIndependentSummary':
          'فعال‌سازی TUN ویندوز مستقل از وضعیت پروکسی سیستم.',
      'clearSystemProxy': 'پاک‌کردن پروکسی سیستم',
      'clearSystemProxySummary':
          'غیرفعال‌کردن پروکسی گیرکرده Windows و پاک‌کردن داده بازیابی niraN.',
      'systemProxyEnabledToast': 'پروکسی سیستم فعال شد',
      'systemProxyClearedToast': 'پروکسی سیستم پاک شد',
      'showRecentLogsOnHome': 'نمایش گزارش‌های اخیر در خانه',
      'showRecentLogsOnHomeSummary':
          'نمایش زنده و فشرده آخرین رویدادهای پاک‌سازی‌شده هسته.',
      'startWithWindows': 'اجرای خودکار niraN هنگام ورود به ویندوز',
      'startWithWindowsSummary':
          'اجرای خودکار همین نسخه Portable هنگام ورود به حساب ویندوز.',
      'recentLogs': 'گزارش‌های اخیر',
      'connectionMode': 'حالت اتصال',
      'vpn': 'حالت VPN',
      'proxy': 'حالت پروکسی',
      'enableLocalDns': 'فعال‌سازی DNS محلی',
      'enableLocalDnsSummary': 'ارسال ترافیک DNS به ماژول DNS هسته Xray.',
      'enableFakeDns': 'فعال‌سازی FakeDNS',
      'enableFakeDnsSummary': 'استفاده از پاسخ‌های مصنوعی DNS همراه Sniffing.',
      'vpnDns': 'DNS رابط VPN',
      'vpnInterfaceAddress': 'آدرس رابط VPN',
      'vpnInterfaceIpv6Address': 'آدرس IPv6 رابط VPN',
      'invalidVpnIpv6Address': 'یک آدرس IPv6 معتبر همراه CIDR وارد کنید.',
      'localSocksPort': 'پورت SOCKS محلی',
      'localHttpPort': 'پورت HTTP محلی',
      'realPingConcurrency': 'تعداد تست هم‌زمان تأخیر واقعی',
      'realDelayUrl': 'آدرس تست تأخیر واقعی',
      'realDelayTimeout': 'مهلت تست تأخیر واقعی',
      'delayTest': 'تست تأخیر',
      'localProxy': 'پروکسی محلی',
      'tunSettings': 'تنظیمات TUN',
      'invalidUrl': 'یک آدرس معتبر HTTP یا HTTPS وارد کنید.',
      'coreSettings': 'تنظیمات هسته',
      'advancedSettings': 'تنظیمات پیشرفته',
      'enableIpv6': 'فعال‌سازی IPv6',
      'enableIpv6Summary': 'اجازه به Xray برای اتصال به مقصدهای IPv6.',
      'preferIpv6': 'اولویت IPv6',
      'preferIpv6Summary': 'هنگام یافتن آدرس سرور پروکسی، IPv6 در اولویت باشد.',
      'vpnMtu': 'MTU شبکه VPN',
      'vpnMtuSummary': 'محدوده معتبر: ۱۲۸۰ تا ۹۰۰۰',
      'enableSniffing': 'فعال‌سازی Sniffing',
      'sniffingSummary': 'تشخیص دامنه مقصد از ترافیک HTTP، TLS و QUIC.',
      'enableRouteOnly': 'فعال‌سازی routeOnly',
      'routeOnlySummary':
          'استفاده از دامنه تشخیص‌داده‌شده فقط برای مسیریابی محلی.',
      'blockQuic': 'مسدودسازی QUIC (UDP/443)',
      'blockQuicSummary': 'راهکار سازگاری اختیاری؛ به‌صورت پیش‌فرض خاموش است.',
      'mux': 'مالتی‌پلکس (Mux)',
      'muxSummary': 'ترکیب اتصال‌های سازگار VLESS/VMess؛ پیش‌فرض خاموش است.',
      'muxConcurrency': 'هم‌زمانی Mux',
      'remoteDns': 'DNS راه‌دور',
      'directDns': 'DNS مستقیم',
      'directDnsSummary': 'استفاده از DNS جدا برای مقصدهای مستقیم.',
      'directDnsAddress': 'آدرس DNS مستقیم',
      'dnsQueryStrategy': 'راهبرد درخواست DNS',
      'dnsQueryStrategySummary': 'خانواده آدرس خروجی از DNS داخلی Xray.',
      'dnsParallelQuery': 'درخواست هم‌زمان DNS',
      'dnsParallelQuerySummary': 'پرس‌وجوی هم‌زمان از resolverهای مناسب.',
      'dnsServeStale': 'پاسخ DNS منقضی‌شده',
      'dnsServeStaleSummary': 'استفاده موقت از cache قبلی هنگام تازه‌سازی.',
      'directTargetStrategy': 'راهبرد مقصد مستقیم',
      'proxyTargetStrategy': 'راهبرد مقصد پروکسی',
      'proxyDialStrategy': 'راهبرد اتصال به پروکسی',
      'happyEyeballs': 'Happy Eyeballs',
      'happyEyeballsSummary': 'رقابت TCP بین آدرس‌های IPv4 و IPv6 سرور.',
      'resetSettings': 'بازنشانی تنظیمات',
      'resetSettingsBody': 'همه تنظیمات niraN به مقدار پیش‌فرض برگردند؟',
      'settingsReset': 'تنظیمات بازنشانی شد.',
      'domainStrategy': 'راهبرد دامنه',
      'subscriptionUpdate': 'به‌روزرسانی اشتراک',
      'autoUpdate': 'به‌روزرسانی خودکار',
      'updateInterval': 'فاصله به‌روزرسانی',
      'lastUpdated': 'آخرین به‌روزرسانی',
      'updates': 'به‌روزرسانی برنامه',
      'currentVersion': 'نسخه فعلی',
      'checkForUpdates': 'بررسی به‌روزرسانی',
      'newVersionAvailable': 'نسخه جدید موجود است',
      'viewRelease': 'مشاهده انتشار',
      'upToDate': 'برنامه به‌روز است.',
      'updateCheckFailed':
          'ارتباط با GitHub ممکن نشد. اتصال اینترنت را بررسی و دوباره تلاش کنید.',
      'updateDownload': 'دانلود به‌روزرسانی',
      'downloading': 'در حال دانلود',
      'paused': 'متوقف‌شده',
      'cancelled': 'لغوشده',
      'verifying': 'در حال اعتبارسنجی',
      'downloaded': 'دانلودشده',
      'readyToUpdate': 'آماده به‌روزرسانی',
      'closingApp': 'در حال بستن برنامه',
      'extracting': 'در حال استخراج',
      'replacingFiles': 'در حال جایگزینی فایل‌ها',
      'renamingFolder': 'در حال تغییر نام پوشه',
      'restartingApp': 'در حال اجرای مجدد',
      'updateFailed': 'به‌روزرسانی ناموفق بود',
      'completed': 'کامل‌شده',
      'cancelDownload': 'لغو دانلود',
      'resumeDownload': 'ادامه دانلود',
      'installUpdate': 'نصب به‌روزرسانی',
      'openDownloadFolder': 'بازکردن پوشه دانلود',
      'performanceModeDialogBody':
          'اگر دستگاه شما قدیمی است یا رابط کاربری کند به نظر می‌رسد، حالت عملکرد با کاهش جلوه‌ها و حرکت‌ها پاسخ‌گویی و مصرف باتری را بهتر می‌کند.',
      'enable': 'فعال‌سازی',
      'keepFullEffects': 'حفظ جلوه‌های کامل',
      'hours6': '۶ ساعت',
      'hours12': '۱۲ ساعت',
      'hours24': '۲۴ ساعت',
      'never': 'هرگز',
      'telegram': 'کانال تلگرام',
      'telegramSubtitle': 'به‌روزرسانی‌ها، اختلال‌ها و اخبار سرورها',
      'joinTelegramTitle': 'از وضعیت سرویس باخبر بمانید',
      'joinTelegramBody':
          'برای دریافت به‌روزرسانی‌ها، اختلال‌ها و اخبار سرورها به کانال تلگرام ما بپیوندید.',
      'joinTelegram': 'عضویت در تلگرام',
      'later': 'بعداً',
      'dontShowAgain': 'دیگر نمایش نده',
      'about': 'درباره',
      'coreVersion': 'هسته Xray',
      'packageName': 'شناسه بسته',
      'noLogs': 'هنوز گزارشی وجود ندارد',
      'clear': 'پاک‌کردن',
      'clearLogs': 'گزارش‌ها پاک شوند؟',
      'clearLogsBody': 'رویدادهای محلی و پالایش‌شده برنامه حذف می‌شوند.',
      'operationFailed': 'عملیات ناموفق بود',
      'administratorRequiredTitle': 'نیاز به دسترسی Administrator',
      'administratorRequiredMessage':
          'حالت TUN به دسترسی Administrator نیاز دارد. لطفاً niraN را ببندید و دوباره با گزینه «Run as administrator» اجرا کنید.',
      'subscriptionUsageUnknown': 'اطلاعات مصرف در دسترس نیست',
      'serverCount': 'سرور',
      'ipProvider': 'آدرس بررسی اطلاعات اتصال فعلی',
      'applyNextConnection': 'تغییرات در اتصال بعدی اعمال می‌شوند.',
      'copy': 'کپی',
      'logCopied': 'لاگ کپی شد',
      'enableUdp': 'فعال‌سازی UDP',
      'enableUdpSummary': 'پذیرش ترافیک UDP از پراکسی SOCKS محلی.',
      'allowLanConnections': 'اجازه اتصال از شبکه محلی',
      'allowLanConnectionsSummary':
          'پورت‌های پراکسی محلی را روی رابط انتخاب‌شده در دسترس می‌گذارد.',
      'localListenAddress': 'آدرس Listen محلی',
      'xrayLogLevel': 'سطح لاگ Xray',
      'sniffingType': 'پروتکل‌های Sniffing',
      'enableFragment': 'قطعه‌قطعه‌سازی TLS ClientHello',
      'fragmentSummary':
          'اتصال بالادستی Xray را از خروجی Freedom Fragment عبور می‌دهد.',
      'fragmentParameters': 'پارامترهای Fragment',
      'fragmentPackets': 'Packets',
      'fragmentLength': 'بازه طول',
      'fragmentInterval': 'بازه تأخیر',
      'fragmentMaxSplit': 'حداکثر تعداد قطعه‌ها',
      'defaultFingerprint': 'اثر انگشت پیش‌فرض TLS',
      'defaultUserAgent': 'User-Agent پیش‌فرض WebSocket',
      'domesticDns': 'DNS داخلی',
      'notSet': 'تنظیم نشده',
      'invalidValue': 'مقدار نامعتبر است',
      'profileTlsSettings': 'تنظیمات TLS/CDN پروفایل',
      'fingerprint': 'اثر انگشت TLS',
      'cipherSuites': 'مجموعه‌های رمز TLS',
      'cipherSuitesHint': 'نام‌های Xray TLS با جداکننده دونقطه',
      'finalMaskHint': 'شیء JSON خام FinalMask برای Xray',
      'invalidJson': 'JSON نامعتبر است',
      'finalMaskObjectError': 'FinalMask باید یک شیء JSON باشد.',
      'allowInsecureUnsupported':
          'این لینک allowInsecure می‌خواهد. Xray 26.7.28 دیگر آن را پشتیبانی نمی‌کند؛ اعتبارسنجی گواهی فعال می‌ماند.',
      'copyShareLink': 'کپی لینک اشتراک‌گذاری',
      'shareLinkCopied': 'لینک کپی شد',
      'emptyServers': 'هیچ سرور VLESS، VMess یا Trojan معتبری بارگذاری نشد.',
    },
  };
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture(AppStrings(locale));

  @override
  bool shouldReload(_AppStringsDelegate old) => false;
}

extension AppStringsContext on BuildContext {
  String s(String key) => AppStrings.of(this).text(key);
}
